export const translate = {
  en: {
    home: "Home",
    about: "About Us",
    posts: "Listings",
  
    accroche: "Connect with Global Agricultural Markets",
    textacrroche: "Buy and sell spices, crops, and products directly with farmers, cooperatives, and businesses worldwide.",
    btnStart: "Start Trading",
  
    abouttitle1: "Connect Globally",
    abouttext1: "Connect directly with producers, cooperatives, and businesses without limits.",
    abouttitle2: "Fair & Transparent Deals",
    abouttext2: "Compare prices and quality in an open marketplace.",
    abouttitle3: "Direct Trade, Better Margins",
    abouttext3: "Better prices for buyers and better margins for sellers.",
  
    titleCategorie: "Product Categories",
    catBeans: "Beans",
    catCereals: "Cereals",
    catVeg: "Fruits & Vegetables",
    catNuts: "Nuts",
    catSpices: "Spices",
    catRoots: "Roots",
  
    titleFeature: "Recent Listings",
    All: "All",
    Selling: "Selling",
    Buying: "Buying",
  
    btnPlaceBid: "Place a Bid",
    btnMakeOffer: "Make an Offer",
    viewLess: "View Less",
    viewMore: "View More",
  
    abttitle1: "High-Quality Products",
    abttext1: "From trusted producers",
    abttitle2: "Empowering Local Farmers",
    abttext2: "Supporting sustainable growth",
  
    preFttitle: "Empowering farmers and producers through direct trade",
    preFtText: "Our marketplace connects farmers, cooperatives, and producers directly with buyers worldwide.",
    btnPost: "Post an Offer",
    FtText: "Together, we are building a fair and sustainable future for agriculture.",
  
    quickLinks: "Quick Links",
    resources: "Resources",
    contact: "Contact",
    faq: "FAQ",
    pa: "Precision Agriculture",
    shipping: "Shipping & Delivery",
    privacyPolicy: "Privacy Policy",
    termsOfUse: "Terms of Service",
  
    stayConnected: "Stay Connected",
    subscribeText: "Subscribe to our newsletter for updates and special offers.",
    copy: "2025 SmartSaha Marketplace. All rights reserved.",
  
    search: "Search...",
    type: "Type",
    location: "Location",
    priceRange: "Price Range",
    apply: "Apply Filters",
  
    myListings: "My Listings",
    newListings: "New Listings",
    product: "Products",
    quantity: "Quantity",
    price: "Price",
    category: "Category",
    date: "Date",
    actions: "Actions",
    page: "Page",
    sur: "of",
    prev: "Previous",
    next: "Next",
  
    noListingsFound: "No listings found",
    createTitle: "Create a New Listing",
    title: "Title",
    desc: "Description",
    listingsType: "Listing Type",
    image: "Image",
    currency: "Currency",
    btnSave: "Save",
  
    bidFor: "Bids for",
    bestOffer: "Best Offer",
    btnaccept: "Accept",
    noBidFound: "No bids for this listing.",
    publishedOn: "Published on",
    MsgBuyer: "Message to Buyer",
    cancel: "Cancel",
    btndecline: "Decline",
  
    mybid: "My Bids",
    monOffre: "My Offer",
    noFoundMyBid: "You have not placed any bids yet.",
    btnCancel: "Cancel Bid",
    comfirmCancel: "Confirm Cancellation",
    confirmText: "Do you really want to cancel this bid?",
    confirm: "Confirm",
    gotopost: "View Listing",
  
    receivedBid: "Received Bids",
    msgBid: "Bid Message",
    negocier: "Negotiate",
    noReceivedBidFound: "You have not received any bids yet.",
  
    chats: "Chats",
    dashboard: "Dashboard",
    logout: "Sign Out",
    bid: "Bids",
    chatbox: "Chat",
  
    deleteChat: "Delete Chat",
    confirmDelete: "Confirm Deletion",
    confirmDelText: "Do you really want to delete this chat? This action cannot be undone.",
    delete: "Delete",
    confirmDeleteReport:
      "This action is <strong>irreversible</strong>.<br />The post will be marked as <span class='text-red-600 font-medium'>deleted</span> and all related reports will be approved.",
  
    acceptedBid: "Bid Accepted!",
    bidOf: "Bid from",
    acceptedAt: "Accepted at",
    priceProposed: "Proposed Price",
    msg: "Message",
    send: "Send",
  
    categoryProduct: "Product Categories",
    addCategory: "Add Category",
    edit: "Edit",
    add: "Add",
    noCategoryFound: "No categories available.",
  
    validationPosts: "Listing Validation",
    validate: "Approve",
    reject: "Reject",
    validatePost: "Validate Listing",
    rejectPost: "Reject Listing",
  
    catPlaceholder: "Cereals...",
    productTitle: "Product & Unit Management",
    productText: "Organize products, define units, and structure your inventory.",
    products: "Products",
    units: "Units",
    productName: "Name",
    productDesc: "Description",
    unit: "Unit",
    abrev: "Abbreviation",
  
    userTitle: "User Management",
    username: "Username",
    email: "Email",
    password: "Password",
    justificatifUrl: "Document URL",
  
    userVerified: "Verified Users",
    userPending: "Pending Users",
    viewNotVerified: "View Unverified",
    viewVerified: "View Verified",
  
    user: "User",
    verified: "Verified",
    verify: "Verify",
    actif: "Active",
    inactif: "Inactive",
    justificatif: "Document",
    viewDoc: "View Document",
    nodoc: "No Document",
  
    verifiedAccount: "Verified Account",
    notverifiedAccount: "Unverified Account",
    status: "Status",
    annonces: "Listings",
    noAnnoncesFound: "This user has not posted any listings yet.",
    report: "Report Listing",
    reportPlaceholder: "Explain the reason for reporting...",
    reports: "Reports",
    reportstitle: "Listing Reports",
    approveReports: "Approve Report",
    userReview: "User Reviews",
    viewReports: "View Reports",
    ready: "Ready to start?",
    join: "Join thousands of users",
    joinTxt: "Buying, selling & negotiating smarter every day.",
    howItWork: "How It Works",
  
    totalUsers: "Total Users",
    verifiedUsers: "Verified Users",
    unverifiedUsers: "Unverified Users",
    usersByCategory: "Users by Category",
    postsStatus: "Listings Status",
    soldPosts: "Sold Listings",
    dashboardText: "Your activity overview",
    global: "Global",
    last7: "Last 7 days",
    lastMoth: "Last Month",
    year: "This Year",
    annoncesEvolution: "Sold listings evolution",
    soldPostsPerWeek: "Sold listings per week",
    reportsPerWeek: "Reports per week",
    notif: "Notifications",
    catText: "Manage your product categories",

    aboutTitle: "About SmartSaha Marketplace",
    aboutText: "Connecting farmers, producers, and global buyers through a trusted and transparent marketplace that empowers local agriculture worldwide.",
    whoWeAre: "Who We Are",
    whores1: "SmartSaha Marketplace is a digital platform designed to bring together farmers, cooperatives, and businesses across the globe. Our mission is to simplify trade by connecting producers directly with clients, fostering growth and innovation in agriculture.",
    whores2: "We believe in empowering rural communities through fair trade, transparent transactions, and digital inclusion — helping small-scale farmers reach global markets effortlessly.",
    mission: "Our Mission & Vision",
    missionRes1: "We are committed to transforming the agricultural value chain through innovation, transparency, and sustainable partnerships.",
    signin: "Sign in"
  },
  
  fr: {
    home: "Accueil",
    about: "À propos",
    posts: "Annonces",
  
    accroche: "Connectez-vous aux marchés agricoles mondiaux",
    textacrroche: "Achetez et vendez épices, cultures et produits directement avec les producteurs, coopératives et entreprises dans le monde.",
    btnStart: "Commencer le trading",
  
    abouttitle1: "Connexion mondiale",
    abouttext1: "Connectez-vous directement avec les producteurs, coopératives et entreprises, sans limites.",
    abouttitle2: "Transactions justes et transparentes",
    abouttext2: "Comparez les prix et la qualité sur un marché ouvert.",
    abouttitle3: "Commerce direct, meilleures marges",
    abouttext3: "De meilleurs prix pour les acheteurs et de meilleures marges pour les vendeurs.",
  
    titleCategorie: "Catégories de produits",
    catBeans: "Haricots",
    catCereals: "Céréales",
    catVeg: "Fruits & Légumes",
    catNuts: "Noix",
    catSpices: "Épices",
    catRoots: "Racines",
  
    titleFeature: "Annonces récentes",
    All: "Tous",
    Selling: "En vente",
    Buying: "En achat",
  
    btnPlaceBid: "Placer une enchère",
    btnMakeOffer: "Faire une offre",
    viewLess: "Voir moins",
    viewMore: "Voir plus",
  
    abttitle1: "Produits de haute qualité",
    abttext1: "Issus de producteurs de confiance",
    abttitle2: "Soutenir les producteurs locaux",
    abttext2: "Favoriser une croissance durable",
  
    preFttitle: "Autonomiser les producteurs grâce au commerce direct",
    preFtText: "Notre marketplace connecte directement les agriculteurs, coopératives et producteurs aux acheteurs du monde entier.",
    btnPost: "Publier une offre",
    FtText: "Ensemble, construisons un avenir agricole équitable et durable.",
  
    quickLinks: "Liens rapides",
    resources: "Ressources",
    contact: "Contact",
    faq: "FAQ",
    pa: "Agriculture de précision",
    shipping: "Expédition & Livraison",
    privacyPolicy: "Politique de confidentialité",
    termsOfUse: "Conditions d'utilisation",
  
    stayConnected: "Restez connecté",
    subscribeText: "Abonnez-vous à notre newsletter pour recevoir les mises à jour et offres spéciales.",
    copy: "2025 SmartSaha Marketplace. Tous droits réservés.",
  
    search: "Rechercher...",
    type: "Type",
    location: "Localisation",
    priceRange: "Fourchette de prix",
    apply: "Appliquer les filtres",
  
    myListings: "Mes annonces",
    newListings: "Nouvelles annonces",
    product: "Produits",
    quantity: "Quantité",
    price: "Prix",
    category: "Catégorie",
    date: "Date",
    actions: "Actions",
    page: "Page",
    sur: "sur",
    prev: "Précédent",
    next: "Suivant",
  
    noListingsFound: "Aucune annonce trouvée",
    createTitle: "Créer une nouvelle annonce",
    title: "Titre",
    desc: "Description",
    listingsType: "Type d’annonce",
    image: "Image",
    currency: "Devise",
    btnSave: "Enregistrer",
  
    bidFor: "Enchères pour",
    bestOffer: "Meilleure offre",
    btnaccept: "Accepter",
    noBidFound: "Aucune enchère pour cette annonce.",
    publishedOn: "Publié le",
    MsgBuyer: "Message à l’acheteur",
    cancel: "Annuler",
    btndecline: "Refuser",
  
    mybid: "Mes enchères",
    monOffre: "Mon offre",
    noFoundMyBid: "Vous n'avez encore placé aucune enchère.",
    btnCancel: "Annuler l’enchère",
    comfirmCancel: "Confirmer l’annulation",
    confirmText: "Voulez-vous vraiment annuler cette enchère ?",
    confirm: "Confirmer",
    gotopost: "Voir l’annonce",
  
    receivedBid: "Enchères reçues",
    msgBid: "Message de l’enchère",
    negocier: "Négocier",
    noReceivedBidFound: "Aucune enchère reçue pour le moment.",
  
    chats: "Discussions",
    dashboard: "Tableau de bord",
    logout: "Se déconnecter",
    bid: "Enchères",
    chatbox: "Messagerie",
  
    deleteChat: "Supprimer la discussion",
    confirmDelete: "Confirmer la suppression",
    confirmDelText: "Voulez-vous vraiment supprimer cette discussion ? Cette action est irréversible.",
    delete: "Supprimer",
    confirmDeleteReport:
      "Cette action est <strong>irréversible</strong>.<br />L'annonce sera marquée comme <span class='text-red-600 font-medium'>supprimée</span> et tous les rapports associés seront validés.",
  
    acceptedBid: "Enchère acceptée !",
    bidOf: "Enchère de",
    acceptedAt: "acceptée le",
    priceProposed: "Prix proposé",
    msg: "Message",
    send: "Envoyer",
  
    categoryProduct: "Catégories de produits",
    addCategory: "Ajouter une catégorie",
    edit: "Modifier",
    add: "Ajouter",
    noCategoryFound: "Aucune catégorie disponible.",
  
    validationPosts: "Validation des annonces",
    validate: "Valider",
    reject: "Rejeter",
    validatePost: "Valider l'annonce",
    rejectPost: "Rejeter l'annonce",
  
    catPlaceholder: "Céréales...",
    productTitle: "Gestion des produits & unités",
    productText: "Organisez vos produits, définissez les unités et structurez votre inventaire.",
    products: "Produits",
    units: "Unités",
    productName: "Nom",
    productDesc: "Description",
    unit: "Unité",
    abrev: "Abréviation",
  
    userTitle: "Gestion des utilisateurs",
    username: "Nom d'utilisateur",
    email: "Email",
    password: "Mot de passe",
    justificatifUrl: "URL du justificatif",
  
    userVerified: "Utilisateurs vérifiés",
    userPending: "Utilisateurs en attente",
    viewNotVerified: "Voir non vérifiés",
    viewVerified: "Voir vérifiés",
  
    user: "Utilisateur",
    verified: "Vérifié",
    verify: "Vérifier",
    actif: "Actif",
    inactif: "Inactif",
    justificatif: "Justificatif",
    viewDoc: "Voir le document",
    nodoc: "Aucun justificatif",
  
    verifiedAccount: "Compte vérifié",
    notverifiedAccount: "Compte non vérifié",
    status: "Statut",
    annonces: "Annonces",
    noAnnoncesFound: "Cet utilisateur n’a encore publié aucune annonce.",
  
    report: "Signaler l'annonce",
    reportPlaceholder: "Expliquez la raison du signalement...",
    reports: "Rapports",
    reportstitle: "Rapports d'annonces",
    approveReports: "Valider le rapport",
    userReview: "Avis des utilisateurs",
    viewReports: "Voir les rapports",
    ready: "Prêt à commencer ?",
    join: "Rejoignez des milliers d'utilisateurs",
    joinTxt: "Acheter, vendre et négocier plus intelligemment chaque jour.",
    howItWork: "Comment ça marche",
  
    totalUsers: "Total d'utilisateurs",
    verifiedUsers: "Utilisateurs vérifiés",
    unverifiedUsers: "Utilisateurs non vérifiés",
    usersByCategory: "Utilisateurs par catégorie",
    postsStatus: "Statut des annonces",
    soldPosts: "Annonces conclues",
    dashboardText: "Vue d'ensemble de votre activité",
    global: "Global",
    last7: "7 derniers jours",
    lastMoth: "Mois dernier",
    year: "Cette année",
    annoncesEvolution: "Évolution des annonces conclues",
    soldPostsPerWeek: "Annonces conclues par semaine",
    reportsPerWeek: "Rapports par semaine",
    notif: "Notifications",
    catText: "Gérez vos catégories de produits",

    aboutTitle: "À propos de SmartSaha Marketplace",
    aboutText: "Connecter les agriculteurs, producteurs et acheteurs mondiaux via une marketplace fiable et transparente qui valorise l'agriculture locale dans le monde entier.",
    whoWeAre: "Qui nous sommes",
    whores1: "SmartSaha Marketplace est une plateforme numérique conçue pour réunir les agriculteurs, coopératives et entreprises du monde entier. Notre mission est de simplifier le commerce en connectant directement les producteurs aux clients, favorisant la croissance et l'innovation dans l'agriculture.",
    whores2: "Nous croyons en l'autonomisation des communautés rurales grâce au commerce équitable, à la transparence des transactions et à l'inclusion numérique — aidant les petits producteurs à atteindre les marchés mondiaux facilement.",
    mission: "Notre mission & vision",
    missionRes1: "Nous nous engageons à transformer la chaîne de valeur agricole grâce à l'innovation, la transparence et des partenariats durables.",
    signin: "Se connecter"

  },
  mg: {
    home: "Fandraisana",
    about: "Momba anay",
    posts: "Tolotra",
  
    accroche: "Mifandray amin'ny tsena fambolena maneran-tany",
    textacrroche: "Mividy sy mivarotra zava-manitra, vokatra sy entana mivantana amin'ny tantsaha, fikambanana ary orinasa manerantany.",
    btnStart: "Atombohy ny varotra",
  
    abouttitle1: "Fifandraisana maneran-tany",
    abouttext1: "Mifandray mivantana amin'ny mpamokatra, fikambanana ary orinasa, tsy misy fetra.",
    abouttitle2: "Varotra mangarahara",
    abouttext2: "Ampitahao ny vidiny sy ny kalitao amin'ny tsena misokatra.",
    abouttitle3: "Varotra mivantana, tombony tsara kokoa",
    abouttext3: "Vidiny tsara ho an'ny mpividy ary tombony lehibe ho an'ny mpivarotra.",
  
    titleCategorie: "Sokajy vokatra",
    catBeans: "Tsaramaso",
    catCereals: "Vary sy katsaka",
    catVeg: "Voankazo sy legioma",
    catNuts: "Voanjo",
    catSpices: "Zava-manitra",
    catRoots: "Faka",
  
    titleFeature: "Tolotra vao haingana",
    All: "Rehetra",
    Selling: "Amidy",
    Buying: "Vidiana",
  
    btnPlaceBid: "Mametraka tolotra",
    btnMakeOffer: "Manao tolo-kevitra",
    viewLess: "Asehoy kely",
    viewMore: "Asehoy bebe kokoa",
  
    abttitle1: "Vokatra tsara kalitao",
    abttext1: "Avy amin'ny mpamokatra atokisana",
    abttitle2: "Manohana ny tantsaha",
    abttext2: "Manampy fitomboana maharitra",
  
    preFttitle: "Manamafy ny tantsaha amin'ny varotra mivantana",
    preFtText: "Mampifandray ny tantsaha, fikambanana ary mpamokatra mivantana amin'ny mpividy manerantany ny tsena anay.",
    btnPost: "Apetraho ny tolotra",
    FtText: "Miara-manangana fambolena marina sy maharitra.",
  
    quickLinks: "Rohy haingana",
    resources: "Loharano",
    contact: "Mifandraisa",
    faq: "FAQ",
    pa: "Fambolena marina",
    shipping: "Fandefasana & Fanaterana",
    privacyPolicy: "Politika manokana",
    termsOfUse: "Fepetra fampiasana",
  
    stayConnected: "Mifandraisa",
    subscribeText: "Misoratra anarana hahazoana vaovao sy tolotra manokana.",
    copy: "2025 SmartSaha Marketplace. Zo rehetra voatokana.",
  
    search: "Karohy...",
    type: "Karazana",
    location: "Toerana",
    priceRange: "Elanelam-bidy",
    apply: "Ampiharo ny sivana",
  
    myListings: "Tolotrako",
    newListings: "Tolotra vaovao",
    product: "Vokatra",
    quantity: "Habetsahana",
    price: "Vidiny",
    category: "Sokajy",
    date: "Daty",
    actions: "Hetsika",
    page: "Pejy",
    sur: "amin'ny",
    prev: "Aloha",
    next: "Manaraka",
  
    noListingsFound: "Tsy misy tolotra hita",
    createTitle: "Hamorona tolotra vaovao",
    title: "Lohateny",
    desc: "Famaritana",
    listingsType: "Karazana tolotra",
    image: "Sary",
    currency: "Vola",
    btnSave: "Tehirizo",
  
    bidFor: "Tolotra ho an'ny",
    bestOffer: "Tolotra tsara indrindra",
    btnaccept: "Ekena",
    noBidFound: "Tsy misy tolotra amin'ity tolotra ity.",
    publishedOn: "Navoaka tamin'ny",
    MsgBuyer: "Hafatra ho an'ny mpividy",
    cancel: "Ajanony",
    btndecline: "Lavina",
  
    mybid: "Ny tolotrako",
    monOffre: "Tolotro",
    noFoundMyBid: "Tsy mbola nanao tolotra ianao.",
    btnCancel: "Ajanony ny tolotra",
    comfirmCancel: "Hamarino ny fanafoanana",
    confirmText: "Tena hanafoana ve ianao ?",
    confirm: "Hamarino",
    gotopost: "Hijery tolotra",
  
    receivedBid: "Tolotra voaray",
    msgBid: "Hafatra",
    negocier: "Hifampiraharaha",
    noReceivedBidFound: "Tsy mbola nahazo tolotra ianao.",
  
    chats: "Resaka",
    dashboard: "Dashboard",
    logout: "Hivoaka",
    bid: "Tolotra",
    chatbox: "Messagerie",
  
    deleteChat: "Hamafa resaka",
    confirmDelete: "Hamarino ny famafana",
    confirmDelText: "Tena hamafa ity resaka ity ve ianao ? Ity hetsika ity dia tsy azo haverina.",
    delete: "Hamafa",
    confirmDeleteReport:
      "Ity hetsika ity dia <strong>tsy azo averina</strong>.<br />Hofafana ny tolotra ary ho ekena avokoa ny tatitra rehetra mifandray aminy.",
  
    acceptedBid: "Ekena ny tolotra !",
    bidOf: "Tolotra avy amin'ny",
    acceptedAt: "nekena tamin'ny",
    priceProposed: "Vidiny natolotra",
    msg: "Hafatra",
    send: "Alefa",
  
    categoryProduct: "Sokajy vokatra",
    addCategory: "Manampy sokajy",
    edit: "Hanova",
    add: "Ampio",
    noCategoryFound: "Tsy misy sokajy.",
  
    validationPosts: "Fanamarinana tolotra",
    validate: "Ekena",
    reject: "Lavina",
    validatePost: "Hamarino ny tolotra",
    rejectPost: "Lavina ny tolotra",
  
    catPlaceholder: "Vary...",
    productTitle: "Fitantanana vokatra & singa",
    productText: "Mandamina ny vokatra, mamaritra ny singa ary mandrafitra ny tahiry.",
    products: "Vokatra",
    units: "Singa",
    productName: "Anarana",
    productDesc: "Famaritana",
    unit: "Singa",
    abrev: "Fohy",
  
    userTitle: "Fitantanana mpampiasa",
    username: "Anaran'ny mpampiasa",
    email: "Mailaka",
    password: "Teny miafina",
    justificatifUrl: "Rohy porofo",
  
    userVerified: "Mpampiasa voamarina",
    userPending: "Miandry fanamarinana",
    viewNotVerified: "Jereo tsy voamarina",
    viewVerified: "Jereo voamarina",
  
    user: "Mpampiasa",
    verified: "Voamarina",
    verify: "Hamarino",
    actif: "Mavitrika",
    inactif: "Tsy mavitrika",
    justificatif: "Porofo",
    viewDoc: "Hijery antontan-taratasy",
    nodoc: "Tsy misy porofo",
  
    verifiedAccount: "Kaonty voamarina",
    notverifiedAccount: "Kaonty tsy voamarina",
    status: "Sata",
    annonces: "Tolotra",
    noAnnoncesFound: "Tsy mbola namoaka tolotra ity mpampiasa ity.",
  
    report: "Hanolotra tatitra",
    reportPlaceholder: "Lazao ny antony handefasana tatitra...",
    reports: "Tatitra",
    reportstitle: "Tatitra momba ny tolotra",
    approveReports: "Ekeo ny tatitra",
    userReview: "Hevitry ny mpampiasa",
    viewReports: "Jereo ny tatitra",
    ready: "Vonona hanomboka ?",
    join: "Miaraha amin'ny mpampiasa an'arivony",
    joinTxt: "Mividy, mivarotra & mifampiraharaha tsara kokoa isan'andro.",
    howItWork: "Ahoana ny fiasany",
  
    totalUsers: "Mpampiasa rehetra",
    verifiedUsers: "Mpampiasa voamarina",
    unverifiedUsers: "Mpampiasa tsy voamarina",
    usersByCategory: "Mpampiasa isaky ny sokajy",
    postsStatus: "Sata tolotra",
    soldPosts: "Tolotra vita",
    dashboardText: "Topi-maso momba ny hetsikao",
    global: "Maneran-tany",
    last7: "7 andro farany",
    lastMoth: "Volana lasa",
    year: "Taona izao",
    annoncesEvolution: "Fivoaran'ny tolotra vita",
    soldPostsPerWeek: "Tolotra vita isan-kerinandro",
    reportsPerWeek: "Tatitra isan-kerinandro",
    notif: "Fampahatsiahivana",
    catText: "Tantano ny sokajy vokatrao",
    aboutTitle: "Momba ny SmartSaha Marketplace",
    aboutText: "Mampifandray ny tantsaha, mpamokatra ary ny mpividy maneran-tany amin'ny alàlan'ny tsena azo itokisana sy mangarahara izay manome hery ny fambolena eo an-toerana manerantany.",
    whoWeAre: "Iza moa izahay",
    whores1: "SmartSaha Marketplace dia sehatra nomerika natao hampivondrona ny tantsaha, fikambanana ary orinasa maneran-tany. Ny tanjonay dia ny hanamora ny varotra amin'ny fampifandraisana mivantana ny mpamokatra amin'ny mpanjifa, manome hery ny fitomboana sy ny fanavaozana eo amin'ny fambolena.",
    whores2: "Mino izahay fa ny fanomezan-kery ny vondrom-piarahamonina ambanivohitra amin'ny alalan'ny varotra ara-drariny, fifanakalozana mangarahara, ary fampidirana nomerika — manampy ny tantsaha madinika hahatratra ny tsena maneran-tany mora foana.",
    mission: "Ny iraka & vina",
    missionRes1: "Manolo-tena hanova ny rojo lanjan'ny fambolena izahay amin'ny alalan'ny fanavaozana, mangarahara, ary fiaraha-miasa maharitra.",
    signin: "Hiditra"

  }
  
  
};
